name: Build Nexus3 Exporter

# 手动触发工作流
on:
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境来运行构建
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出代码
    - name: Setup jdk ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }
    - name: Build with Maven
      run: mvn package -DskipTests  # 构建项目并跳过测试

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nexus3-export-artifact  # 上传的产物名称
        path: target/*.jar  # 构建的产物路径，根据实际情况修改
