name: Build Nexus3 Exporter

# 手动触发工作流
on:
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境来运行构建

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Java JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # 使用 Java 11 来构建项目
        distribution: 'adoptopenjdk'  # 或者选择 openjdk 等 JDK 发行版

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository  # Maven 仓库缓存路径
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # 根据 pom.xml 文件的变化来确定缓存
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn package -DskipTests  # 构建项目并跳过测试

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nexus3-export-artifact  # 上传的产物名称
        path: target/*.jar  # 构建的产物路径，根据实际情况修改
